# Generated by Django 5.0.3 on 2024-03-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playtime",
            name="game",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playtimes",
                to="games.game",
            ),
        ),
        migrations.AlterField(
            model_name="playtime",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="playtimes",
                to="games.player",
            ),
        ),
    ]
