# Generated by Django 5.0.3 on 2024-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_playtime_game_alter_playtime_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
